#!/bin/bash
# Create LaTeX document.
#
# Usage: make_latex path <document_name>.tex <working_directory>
#  <document_name> is the name of the document.

set -e

ascii-t "LaTeX builder!!!"
echo ""
echo ""
echo ""
ascii-t "By Dr Oliver Chalkley"
echo ""
echo ""
echo ""

# if the first or second argument doesn't exist, print usage and exit
if [ -z "${1}" ]; then
  echo "Usage: make_latex <document_name>.tex <working_directory>"
  exit 1
fi

if [ -z "${2}" ]; then
  echo "Usage: make_latex <document_name>.tex <working_directory>"
  exit 1
fi

if [ ! -d "${2}" ]; then
  echo "${2} does not exist."
  exit 1
fi

cd ${2}

echo ""
echo ""
echo ""
echo "Building ${1}..."
echo ""
echo ""
echo ""

full_name=${1}
name=${full_name%.*}

pdflatex ${full_name}
bibtex ${name}
pdflatex ${full_name}
pdflatex ${full_name}
